Removed client exit on wrong json response from server

diff --git a/monopus b/monopus
--- a/monopus
+++ b/monopus
@@ -69,8 +69,8 @@ make_request() {
 
   status=${output_arr[success]}
   if [ "$status" = false ]; then
-    echo "Error: ${output_arr[message]}"
-    exit 1
+    log "Error: ${output_arr[message]}"
+    #exit 1
   fi
   # Here we have variables in output_arr
 }
