change status for not found log in check_bruteforce

diff --git a/check_scripts/check_bruteforce b/check_scripts/check_bruteforce
--- a/check_scripts/check_bruteforce
+++ b/check_scripts/check_bruteforce
@@ -65,8 +65,8 @@ done
 
 # Check exist file
 if [ ! -e $path_to_log ]; then
-    echo "File does not exist -> ${path_to_log}; distib -> ${os}"
-    exit 3
+    echo "check_bruteforce.nofile==${path_to_log}__distib==${os} | failed_login=0;;;;"
+    exit ${state}
 fi
 
 # Extract Failed password from log file
